language: node_js
services:
- postgresql
node_js:
- '8'
cache:
  apt: true
  bundler: true
  directories:
  - "/home/travis/.rvm/"
  - frontend/node_modules
  - backend/.bundle
  - backend/vendor/bundle
install:
- cd ./backend/
- rvm install $(cat .ruby-version)
- bundle install --without production development --deployment --jobs 3 --retry 3
- bundle exec rails db:create db:schema:load
script:
- "./bin/check"
deploy:
  matrix:
  - before_deploy: cd ./backend/
    provider: heroku
    app:
      master: npl-shire-backend-master
      develop: npl-shire-backend-develop
    api_key:
      secure: W/ayZ/xsEizrpTmYdpfxdjE7e6EhYFz8gqq1kRuUIy2uNf1j1zsZffsE3itdtcXfnT9Mg9MTvG1FJY6CQclHH1dFXUGoesr9ISDDCDRQtrZUHz9TjGcLPMK0lFFFy1mn/2WD7NAKDYB5mDC4SQbU3bM4Ltv/WWF1pscPrIvH48Ef5VBGilwoRkHo4ycLhliYIRJqOj8W6oUME3unQqBMrVzQxcx9ra3tzJVJkqRqw0Uas+r9xv5PbeP26dMKlEW/bbCtC3hR0Qz/ptsKOgWe9b80m0caiTYkuw+rR1/rGyotxDjqPAZQ27jqX4skSJOW/EYtFktJ4M3Js/4OK7jxLtnSnjxCNMGrFXzToG7lzv7QUqsPKI4eqXBl2qgUdoRWAD2gQZPnC/hFWW+jfm/wfhfpq3BziuK1GbDXzlLGP5nJMpNl3Ifa4NhAgD9J8OOy2olwSLtv0D0awdP7XOCuJshk0nI8j09l+JFcE9A+OwaUDGqdi040QsivXS4tq3fBNzLuT/7+gaUqR2FdP1bOiyIP/S1i61Nn1dvPgB4BfJ+o0tIDRDnePKM0wlGlqMEzjpCuoPS70Gtd6gjouJ9SbDIwEZQo/5cclFHOHCFp3UqIRrhsnNVe9DiyE+mS/N9xM7xNbqr6Nd156fdBFse3zEpdCKuUnJEDfhWHdxxgbx0=
