language: node_js
services:
  - postgresql
node_js:
  - "8"
cache:
  apt: true
  bundler: true
  directories:
    - /home/travis/.rvm/
    - frontend/node_modules
    - backend/.bundle
    - backend/vendor/bundle
install:
  - cd ./backend/
  - rvm install $(cat .ruby-version)
  - bundle install --without production development --deployment --jobs 3 --retry 3
  - cp config/application.example.yml config/application.yml
  - bundle exec rails db:create db:schema:load
script:
  - ./bin/check
deploy:
  - before_deploy: cd ./backend/
    provider: heroku
    api_key:
      secure: UKfPYmzU+co++Q8IN/Zz8VvnZPQ47Gp/oSzs6fzkYPb6WJfgyHAxDTlOtEvKwTyjcZC4Tu6Zjs3a2wTs56dXvI816WxlC9R5xSC9pQdQt/JNFRZazTTxkcnCl45E4Z+eMmY1E3vxkhteyV736DzRJKjNDRE2HFrwrSD5Ube4DMRfTNf/wRIM30QISun02UIrRU1KyoTe3ITkMPxpvHGHnKrwk3yRLC7u/k1qJ+PA82Pwb38pO20nxzA/gGzMDLqZaO7VIKjl24o6KdxeMQE0ZWd6SU5Bn49i95m5fZnzm2alIs1TPV3GBrfsTFRZua7NAU0euSQl3UcoqvoVVujbwwvxbm3jb/nmpYKCZV6ViaRrj+LQFyYMjgjUm82b7Vh2Gz7mJWdsPlq47e3hGyWaBWp6eSlRIuNwLorZy5Gazq/WKykyQqDrVTTIRGVd0iTVeNTTpoQlFkLBISJHX3TbPXb1P6YI4sQrjg3FqWfyVQNW1Eompr0e5MNqQaSNkSAdI82h6ToVEN5KeVfLOEGMjfh7QPyy6FJ0t2gwFo3N8zlTaFjkoW41zVznlHmn4/IeAalvxmjPRRcLC2KuYIsSny1JCFxSofzV/O+EocB7yVMZ1svyQdvVFG2B1KbtQV26L2K51S4ImdAkGMyx1qJAUJEh4Ei9u+nANQTUovMvmCU=
    app:
      master: npl-shire-backend-master
      develop: npl-shire-backend-develop

