Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - 'spec/**/*.rb'
  - 'config/environments/*.rb'

Naming/FileName:
  Exclude:
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'vendor/bundle/**/*'